# Generated by Django 4.2.22 on 2025-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
