# Generated by Django 4.2.22 on 2025-07-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0002_quiz_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='The text of the answer choice.', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark this if the answer is correct.')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the quiz category.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='The text of the question.', max_length=255)),
                ('marks', models.IntegerField(default=1, help_text='The points awarded for a correct answer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this question was created.')),
                ('category', models.ForeignKey(help_text='The category this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Quiz_App.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='quiz_questions',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='The question this answer is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Quiz_App.question'),
        ),
    ]
